import datetime
import os

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEVERITY_ICON = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}


def _sorted(findings):
    return sorted(findings, key=lambda f: SEVERITY_ORDER.get(f.get("severity", "info"), 5))


def _count(findings):
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info")
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def _write(path, lines):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


def write_code_report(output_path, repo_path, languages, project_type,
                      secret_findings, pattern_findings, dep_findings):
    all_findings = secret_findings + pattern_findings + dep_findings
    counts = _count(all_findings)

    lines = []
    lines.append(f"# Security Audit Report — `{os.path.basename(repo_path.rstrip('/'))}`")
    lines.append("")
    lines.append(f"**Generated:** {datetime.datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"**Target path:** `{repo_path}`")
    lines.append(f"**Project type:** {project_type}")
    lines.append(f"**Languages detected:** {', '.join(languages) if languages else 'none detected'}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    total = sum(counts.values())
    crit_high = counts["critical"] + counts["high"]
    if total == 0:
        lines.append("No issues were flagged by the automated static checks.")
    else:
        lines.append(
            f"Automated analysis found **{total} finding(s)**, of which "
            f"**{crit_high}** are Critical or High severity. "
            "Address Critical/High items first."
        )
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|------:|")
    for sev in ("critical", "high", "medium", "low", "info"):
        lines.append(f"| {SEVERITY_ICON[sev]} {sev.title()} | {counts.get(sev, 0)} |")
    lines.append("")

    lines.append("## Recommended Priority Order")
    lines.append("")
    lines.append("1. **Rotate & remove any leaked secrets** (AWS keys, tokens, private keys, DB passwords).")
    lines.append("2. **Fix injection & RCE patterns** (SQL injection, command injection, insecure deserialization, eval).")
    lines.append("3. **Harden authentication / authorization** and remove debug flags.")
    lines.append("4. **Update vulnerable dependencies**.")
    lines.append("5. **Apply remaining medium/low hardening** (headers, CORS, crypto, etc.).")
    lines.append("")

    if not all_findings:
        lines.append("No automated findings. This does **not** guarantee the codebase is fully secure. "
                     "Pair with manual review, dependency updates, and (for critical apps) a professional pentest.")
    else:
        lines.append("## Detailed Findings")
        lines.append("")
        for f in _sorted(all_findings):
            sev = f.get("severity", "info")
            lines.append(f"### {SEVERITY_ICON[sev]} [{sev.upper()}] {f['type']}")
            lines.append("")
            loc = f.get("file", "")
            line_no = f.get("line", 0)
            if loc:
                rel = loc
                try:
                    rel = os.path.relpath(loc, repo_path)
                except ValueError:
                    pass
                lines.append(f"- **Location:** `{rel}`" + (f" (line {line_no})" if line_no else ""))
            if f.get("snippet"):
                lines.append(f"- **Evidence:** `{f['snippet']}`")
            if f.get("fix"):
                lines.append(f"- **Recommended fix:** {f['fix']}")
            lines.append("")

    lines.append("---")
    lines.append("### Scope & Limitations")
    lines.append("")
    lines.append("- This is **static / pattern-based** analysis plus optional dependency-audit tooling.")
    lines.append("- It does **not** perform dynamic testing, authentication bypass attempts, or exploit verification.")
    lines.append("- False positives are possible; always verify before changing production code.")
    lines.append("- For production / customer-facing systems, treat this as a fast first pass and follow with a proper authorized penetration test.")
    lines.append("")
    lines.append("_Generated by Yemanode v2 — ethical, non-destructive security scanner._")

    return _write(output_path, lines)


def write_api_report(output_path, url, findings):
    counts = _count(findings)
    lines = []
    lines.append(f"# API Security Report — `{url}`")
    lines.append("")
    lines.append(f"**Generated:** {datetime.datetime.now().isoformat(timespec='seconds')}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|------:|")
    for sev in ("critical", "high", "medium", "low", "info"):
        lines.append(f"| {SEVERITY_ICON[sev]} {sev.title()} | {counts.get(sev, 0)} |")
    lines.append("")

    if not findings:
        lines.append("No issues found by the automated passive checks.")
    else:
        lines.append("## Findings")
        lines.append("")
        for f in _sorted(findings):
            sev = f.get("severity", "info")
            lines.append(f"### {SEVERITY_ICON[sev]} [{sev.upper()}] {f['type']}")
            lines.append("")
            if f.get("detail"):
                lines.append(f"- **Detail:** {f['detail']}")
            if f.get("target") and f.get("target") != url:
                lines.append(f"- **Target:** `{f['target']}`")
            if f.get("fix"):
                lines.append(f"- **Recommended fix:** {f['fix']}")
            lines.append("")

    lines.append("---")
    lines.append("### Scope & Limitations")
    lines.append("")
    lines.append("- Checks are **passive / non-destructive**: TLS, headers, CORS, auth presence, HTTP methods, common sensitive paths.")
    lines.append("- No exploit payloads, fuzzing, brute-force, or authentication-bypass attempts are performed.")
    lines.append("- For deeper testing use an authorized DAST tool (OWASP ZAP, Burp Suite, etc.) against a staging environment.")
    lines.append("")
    lines.append("_Generated by Yemanode v2._")

    return _write(output_path, lines)


def write_generic_report(output_path, title, target_desc, findings, extra_notes=None):
    """Used for APK and binary scans."""
    counts = _count(findings)
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"**Target:** `{target_desc}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|------:|")
    for sev in ("critical", "high", "medium", "low", "info"):
        lines.append(f"| {SEVERITY_ICON[sev]} {sev.title()} | {counts.get(sev, 0)} |")
    lines.append("")

    if not findings:
        lines.append("No issues found by the automated static checks.")
    else:
        lines.append("## Findings")
        lines.append("")
        for f in _sorted(findings):
            sev = f.get("severity", "info")
            lines.append(f"### {SEVERITY_ICON[sev]} [{sev.upper()}] {f['type']}")
            lines.append("")
            if f.get("file"):
                lines.append(f"- **Location:** `{f['file']}`" + (f" (line {f['line']})" if f.get("line") else ""))
            if f.get("snippet"):
                lines.append(f"- **Evidence:** `{f['snippet']}`")
            if f.get("fix"):
                lines.append(f"- **Recommended fix:** {f['fix']}")
            lines.append("")

    if extra_notes:
        lines.append("## Notes")
        lines.append("")
        for n in extra_notes:
            lines.append(f"- {n}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by Yemanode v2 — static / non-destructive analysis only._")
    return _write(output_path, lines)
